# Generated by Django 6.0.4 on 2026-04-16 20:35

import core.models.media_object
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional display name; falls back to original_filename when empty.', max_length=200)),
                ('file', models.FileField(max_length=512, upload_to=core.models.media_object.media_object_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, help_text='Optional hex SHA-256 of file bytes: dedupe/idempotency, verify download vs source, detect storage corruption or accidental overwrite.', max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Flexible metadata: e.g. origin (upload/generated/…), width, height, duration_ms, provider, model.')),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_objects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_objects', to='core.workspace')),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['workspace', '-created'], name='core_mediao_workspa_5e9b55_idx')],
            },
        ),
    ]
