# Generated by Django 6.0.4 on 2026-04-16 22:29

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Human-readable type name (unique per organization).', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.JSONField(default=list, help_text='Capability grants for identities of this type: list of objects with at least {"id": "<string>"}.')),
                ('tools_config', models.JSONField(blank=True, default=dict, help_text='Tool policy for this type (allowed tools, provider options, limits). Must be a JSON object.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_types_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_types', to='core.organization')),
            ],
            options={
                'ordering': ('organization_id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CyberIdentity',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Name of this identity in the workspace (e.g. campaign persona).', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Optional per-instance settings (e.g. avatar MediaObject id, tone notes). Must be a JSON object.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyber_identities_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_identities', to='core.workspace')),
                ('identity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cyber_identities', to='core.identitytype')),
            ],
            options={
                'ordering': ('workspace_id', 'display_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='identitytype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='core_identitytype_organization_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='cyberidentity',
            index=models.Index(fields=['workspace', 'identity_type'], name='core_cyberi_workspa_baa3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cyberidentity',
            index=models.Index(fields=['workspace', 'is_active'], name='core_cyberi_workspa_16a9da_idx'),
        ),
    ]
