# Generated by Django 6.0.4 on 2026-04-16 23:04

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberIdentity',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('influencer', 'Influencer'), ('community_manager', 'Community manager'), ('analyst', 'Analyst'), ('personal_assistant', 'Personal assistant')], help_text='Platform-defined identity type sold by the application.', max_length=50)),
                ('display_name', models.CharField(help_text='Name of this identity in the workspace (e.g. campaign persona).', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-identity configuration owned by the org (tone, avatar MediaObject id, profile settings, etc.).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyber_identities_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_identities', to='core.workspace')),
            ],
            options={
                'ordering': ('workspace_id', 'display_name'),
                'indexes': [models.Index(fields=['workspace', 'type'], name='core_cyberi_workspa_a8ba59_idx'), models.Index(fields=['workspace', 'is_active'], name='core_cyberi_workspa_16a9da_idx')],
            },
        ),
    ]
