# Generated by Django 5.2.6 on 2026-04-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agentsessionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsessionlog',
            name='temperature',
        ),
    ]
