# Generated by Django 6.0.4 on 2026-04-16 23:33

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cyberidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityAsset',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('reference_image', 'Reference image'), ('reference_audio', 'Reference audio'), ('policy_document', 'Policy document'), ('brand_guideline', 'Brand guideline'), ('style_reference', 'Style reference')], help_text='Platform-defined category that drives which pipeline consumes the asset.', max_length=40)),
                ('label', models.CharField(blank=True, help_text="Optional human-readable label (e.g. 'front-facing portrait').", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive assets are not fed to generation/RAG pipelines.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form metadata (per-type hints, capture context, provider tags, etc.).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_assets_created', to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.cyberidentity')),
                ('media', models.ForeignKey(help_text='The stored binary this asset points to.', on_delete=django.db.models.deletion.PROTECT, related_name='identity_assets', to='core.mediaobject')),
            ],
            options={
                'ordering': ('identity_id', 'asset_type', '-created'),
                'indexes': [models.Index(fields=['identity', 'asset_type', 'is_active'], name='core_identi_identit_5158e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('core', 'Core'), ('knowledge', 'Knowledge')], default='knowledge', max_length=20)),
                ('content', models.TextField(help_text='The memory text to inject or retrieve.')),
                ('source', models.TextField(blank=True, help_text='Short explanation of why the agent stored this memory (context, task, etc.).')),
                ('topics', models.JSONField(blank=True, default=list, help_text='Topic tags as a list of strings; used to retrieve knowledge memories by topic.')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.cyberidentity')),
            ],
            options={
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['identity', 'memory_type', '-created'], name='core_memory_identit_bca7d5_idx')],
            },
        ),
    ]
