# Generated by Django 6.0.4 on 2026-04-17 05:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_identityasset_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('instagram', 'Instagram'), ('gmail', 'Gmail'), ('telegram', 'Telegram')], max_length=40)),
                ('external_account_id', models.CharField(help_text='Stable id from the provider (IG business account id, gmail address, telegram bot id, ...).', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text="Human label shown in the UI (e.g. '@mybrand', 'support@acme.com').", max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=20)),
                ('encrypted_auth', models.TextField(blank=True, help_text='Fernet-encrypted JSON blob with provider-specific secrets (tokens, cookies, ...).')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret provider configuration: granted scopes, webhook ids, timezone, cached profile metadata, etc. Validated by per-provider pydantic schemas at the service layer.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='core.workspace')),
            ],
            options={
                'ordering': ('workspace_id', 'provider', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationBridge',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('capabilities', models.JSONField(blank=True, default=dict, help_text="Scoped capabilities this identity has on the account (e.g. {'can_post': true, 'can_reply_dm': false}). Validated by a per-provider pydantic schema at the service layer.")),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-bridge runtime configuration set when integrations are wired up.')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_bridges', to='core.cyberidentity')),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_bridges', to='core.integrationaccount')),
            ],
            options={
                'ordering': ('integration_account_id', 'identity_id'),
            },
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['workspace', 'provider', 'status'], name='core_integr_workspa_4f19b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationaccount',
            constraint=models.UniqueConstraint(fields=('workspace', 'provider', 'external_account_id'), name='uniq_integration_per_workspace_provider_external'),
        ),
        migrations.AddIndex(
            model_name='integrationbridge',
            index=models.Index(fields=['integration_account', 'is_active'], name='core_integr_integra_99f161_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationbridge',
            index=models.Index(fields=['identity', 'is_active'], name='core_integr_identit_8a700b_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationbridge',
            constraint=models.UniqueConstraint(fields=('identity', 'integration_account'), name='uniq_identity_integration_bridge'),
        ),
    ]
