# Generated by Django 6.0.4 on 2026-04-29 02:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_integrationaccount_integrationbridge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('integration', 'Integration'), ('web', 'Web chat')], default='integration', help_text='Where this conversation happens (an external integration vs. the in-app web chat).', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Validated against ConversationConfig: external_thread_id, external_user_id, ...')),
                ('last_interaction_at', models.DateTimeField(blank=True, help_text='Timestamp of the last message (denormalized; updated on message write).', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cyber_identity', models.ForeignKey(help_text='Persona on our side that speaks in this conversation.', on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='core.cyberidentity')),
                ('integration_account', models.ForeignKey(blank=True, help_text='Channel this conversation lives on (Telegram bot, Instagram account, ...). Null for web-chat conversations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.integrationaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.workspace')),
            ],
            options={
                'ordering': ('-last_interaction_at', '-created'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text="Provider-qualified event id, e.g. 'instagram.new_comment', 'gmail.new_email'.", max_length=100)),
                ('external_event_id', models.CharField(blank=True, help_text="Provider-side identifier used for idempotency if any. Its optional but it's a good practice to have it.", max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw provider payload.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Set when the orchestrator has handled this event (created executions, ignored, ...).', null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text="Structured error info for the last failed processing attempt, e.g. {'message': ..., 'traceback': ...}.")),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.integrationaccount')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text="Role the agent plays, e.g. 'Telegram Personal Assistant'. Used for display and logging.", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this job does, in plain text. Action it usually takes, accounts that are involved, etc.')),
                ('instructions', models.TextField(blank=True, help_text='Detailed instructions so the agent understands how to perform this job at runtime. Appended to task specific instructions.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Targeting + runtime policy: accounts [{id, provider}], identities [{id, type, config}], triggers, actions, approval_policy, optional output_schema. Can be overridden at task execution level.')),
                ('enabled', models.BooleanField(default=True)),
                ('parent_job_assignment', models.ForeignKey(blank=True, help_text='If this job was spawned by another job (e.g. an AI assistant that created a routine), this points to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_job_assignments', to='core.jobassignment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='core.workspace')),
            ],
            options={
                'ordering': ('workspace_id', 'role_name'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content_text', models.TextField(blank=True, default='', help_text='Plain-text content of the message. Empty string if only structured content is present.')),
                ('content_structured', models.JSONField(blank=True, help_text='Optional structured content (tool calls, rich payloads, attachments metadata).', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'ordering': ('conversation_id', 'created'),
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('requires_approval', models.BooleanField(default=False)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Run inputs: firing trigger, event payload, resolved variables.')),
                ('outputs', models.JSONField(blank=True, default=dict, help_text='Run outputs: final_output, artifact ids, agent_session_log ids, error details.')),
                ('scheduled_to', models.DateTimeField(blank=True, help_text='When this execution should run (deferred / scheduled). Null = run as soon as possible.', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_task_executions', to='core.workspacemember')),
                ('job_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.jobassignment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='core.workspace')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text'), ('external_resource', 'External resource')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Per-kind metadata such as text, format, provider ids, prompts, dimensions, or publish timestamps.')),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='core.integrationaccount')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='core.mediaobject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.workspace')),
                ('task_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.taskexecution')),
            ],
            options={
                'ordering': ('workspace_id', 'kind', '-created'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'status', '-last_interaction_at'], name='core_conver_workspa_6dc46d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['integration_account', '-last_interaction_at'], name='core_conver_integra_6fb627_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['cyber_identity', '-last_interaction_at'], name='core_conver_cyber_i_7c646d_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['integration_account', 'event_type', '-received_at'], name='core_integr_integra_80b3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['processed_at'], name='core_integr_process_299ec3_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id__gt', '')), fields=('integration_account', 'event_type', 'external_event_id'), name='uniq_integration_event_external_id'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['workspace', 'enabled'], name='core_jobass_workspa_9dc311_idx'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['parent_job_assignment'], name='core_jobass_parent__ef0227_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created'], name='core_messag_convers_bd2545_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'role', 'created'], name='core_messag_convers_3a41f1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['workspace', 'status', '-created'], name='core_taskex_workspa_d9ee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['job_assignment', '-created'], name='core_taskex_job_ass_8c05df_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status', 'scheduled_to'], name='core_taskex_status_755f88_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['workspace', 'kind', '-created'], name='core_artifa_workspa_e9ad39_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['task_execution', 'kind'], name='core_artifa_task_ex_41ddd6_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['integration_account', 'kind'], name='core_artifa_integra_7fd307_idx'),
        ),
    ]
