# Generated by Django 6.0.4 on 2026-04-17 16:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_integrationaccount_integrationbridge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(help_text="Role the agent plays, e.g. 'Telegram Message Responder'.", max_length=200)),
                ('description', models.TextField(blank=True, help_text='What this job does, in plain text.')),
                ('instructions', models.TextField(blank=True, help_text='Detailed instructions so the agent understands how to perform this job at runtime.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Targeting + runtime policy: accounts, identities, triggers, actions, approval_policy, optional output_schema.')),
                ('enabled', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='core.workspace')),
            ],
            options={
                'ordering': ('workspace_id', 'role_name'),
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Run inputs: firing trigger, event payload, resolved variables.')),
                ('outputs', models.JSONField(blank=True, default=dict, help_text='Run outputs: final_output, artifact ids, agent_session_log ids, error details.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_task_executions', to='core.workspacemember')),
                ('job_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.jobassignment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='core.workspace')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form per-kind metadata (caption, summary, generator params, prompt, duration, size, etc, format (eg: markdown, html, etc, or png, jpg, etc)).')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='core.mediaobject')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.taskexecution')),
            ],
            options={
                'ordering': ('task_execution_id', 'kind', '-created'),
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text="Provider-qualified event id, e.g. 'instagram.new_comment', 'gmail.new_email'.", max_length=100)),
                ('external_event_id', models.CharField(blank=True, help_text="Provider-side identifier used for idempotency if any. Its optional but it's a good practice to have it.", max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw provider payload.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Set when the orchestrator has handled this event (created executions, ignored, ...).', null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text="Structured error info for the last failed processing attempt, e.g. {'message': ..., 'traceback': ...}.")),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.integrationaccount')),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['integration_account', 'event_type', '-received_at'], name='core_integr_integra_80b3c3_idx'), models.Index(fields=['processed_at'], name='core_integr_process_299ec3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_event_id__gt', '')), fields=('integration_account', 'event_type', 'external_event_id'), name='uniq_integration_event_external_id')],
            },
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['workspace', 'enabled'], name='core_jobass_workspa_9dc311_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['workspace', 'status', '-created'], name='core_taskex_workspa_d9ee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['job_assignment', '-created'], name='core_taskex_job_ass_8c05df_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['task_execution', 'kind'], name='core_artifa_task_ex_41ddd6_idx'),
        ),
    ]
