# Generated by Django 6.0.4 on 2026-04-17 08:23

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_integrationaccount_integrationbridge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('creation_details', models.JSONField(blank=True, default=dict, help_text='Who/what created this assignment (user, agent, reason).')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Assignment configuration: trigger, target accounts and identities, input overrides, approval policy.')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('task_template_id', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('post', 'Post'), ('reply', 'Reply'), ('report', 'Report'), ('notification', 'Notification'), ('custom', 'Custom')], max_length=40)),
                ('name', models.CharField(help_text='Short label shown in the UI.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text="System prompt / instructions the agent receives for this template. May reference input variables with '{{input_name}}' placeholders, resolved at execution time.")),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='Pydantic/JSON schema plus defaults for the input variables consumed by ``instructions``.')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='Pydantic JSON schema describing the expected output the agent must return.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Template-level configuration (allowed tools, model/provider, rate limits, ...).')),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='core.workspace')),
            ],
            options={
                'ordering': ('workspace_id', 'type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Run payload: resolved inputs, structured outputs, trigger info, errors, external delivery metadata.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_task_executions', to='core.workspacemember')),
                ('task_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.taskassignment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='core.workspace')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.tasktemplate')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.tasktemplate'),
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text="Provider-qualified event id, e.g. 'instagram.new_comment', 'gmail.new_email'.", max_length=100)),
                ('external_event_id', models.CharField(blank=True, help_text="Provider-side identifier used for idempotency if any. Its optional but it's a good practice to have it.", max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw provider payload.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Set when the orchestrator has handled this event (created executions, ignored, ...).', null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, help_text="Structured error info for the last failed processing attempt, e.g. {'message': ..., 'traceback': ...}.")),
                ('integration_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.integrationaccount')),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['integration_account', 'event_type', '-received_at'], name='core_integr_integra_80b3c3_idx'), models.Index(fields=['processed_at'], name='core_integr_process_299ec3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_event_id__gt', '')), fields=('integration_account', 'event_type', 'external_event_id'), name='uniq_integration_event_external_id')],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('text', 'Text'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form per-kind metadata (caption, summary, generator params, prompt, duration, size, etc, format (eg: markdown, html, etc, or png, jpg, etc)).')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='core.mediaobject')),
                ('task_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.taskexecution')),
            ],
            options={
                'ordering': ('task_execution_id', 'kind', '-created'),
                'indexes': [models.Index(fields=['task_execution', 'kind'], name='core_artifa_task_ex_41ddd6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['workspace', 'type', 'enabled'], name='core_taskte_workspa_099b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['workspace', 'status', '-created'], name='core_taskex_workspa_d9ee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task_template', 'status'], name='core_taskex_task_te_f0a2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['task_assignment', '-created'], name='core_taskex_task_as_b51182_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task_template', 'enabled'], name='core_taskas_task_te_1ec796_idx'),
        ),
    ]
