# Generated by Django 6.0.4 on 2026-04-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobassignment_taskexecution_artifact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignment',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Targeting + runtime policy: accounts [{id, provider}], identities [{id, type, config}], triggers, actions, approval_policy, optional output_schema. Can be overridden at task execution level.'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='description',
            field=models.TextField(blank=True, help_text='What this job does, in plain text. Action it usually takes, accounts that are involved, etc.'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='instructions',
            field=models.TextField(blank=True, help_text='Detailed instructions so the agent understands how to perform this job at runtime. Appended to task specific instructions.'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='role_name',
            field=models.CharField(help_text="Role the agent plays, e.g. 'Telegram Personal Assistant'. Used for display and logging.", max_length=200),
        ),
    ]
