# Generated by Django 6.0.4 on 2026-04-29 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conversation_integrationevent_jobassignment_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.cyberidentity'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['workspace', 'identity', '-created'], name='core_artifa_workspa_d1b0cc_idx'),
        ),
    ]
