# Generated by Django 6.0.4 on 2026-04-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_artifact_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-kind metadata such as text, extension, provider ids, prompts, dimensions, or publish timestamps.'),
        ),
    ]
