# Generated by Django 6.0.4 on 2026-04-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_jobassignment_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecution',
            name='scheduled_to',
            field=models.DateTimeField(blank=True, help_text='When this execution should run (deferred / scheduled). Null = run as soon as possible.', null=True),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status', 'scheduled_to'], name='core_taskex_status_755f88_idx'),
        ),
    ]
