# Generated by Django 6.0.4 on 2026-04-20 01:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_taskexecution_scheduled_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Validated against ConversationConfig: external_thread_id, external_user_id, ...')),
                ('last_interaction_at', models.DateTimeField(blank=True, help_text='Timestamp of the last message (denormalized; updated on message write).', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-last_interaction_at', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content_text', models.TextField(blank=True, default='', help_text='Plain-text content of the message. Empty string if only structured content is present.')),
                ('content_structured', models.JSONField(blank=True, help_text='Optional structured content (tool calls, rich payloads, attachments metadata).', null=True)),
            ],
            options={
                'ordering': ('conversation_id', 'created'),
            },
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='parent_job_assignment',
            field=models.ForeignKey(blank=True, help_text='If this job was spawned by another job (e.g. an AI assistant that created a routine), this points to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_job_assignments', to='core.jobassignment'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['parent_job_assignment'], name='core_jobass_parent__ef0227_idx'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='cyber_identity',
            field=models.ForeignKey(help_text='Persona on our side that speaks in this conversation.', on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='core.cyberidentity'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='integration_account',
            field=models.ForeignKey(help_text='Channel this conversation lives on (Telegram bot, Instagram account, ...).', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.integrationaccount'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['workspace', 'status', '-last_interaction_at'], name='core_conver_workspa_6dc46d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['integration_account', '-last_interaction_at'], name='core_conver_integra_6fb627_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['cyber_identity', '-last_interaction_at'], name='core_conver_cyber_i_7c646d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created'], name='core_messag_convers_bd2545_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'role', 'created'], name='core_messag_convers_3a41f1_idx'),
        ),
    ]
